In [ ]:
# CALIDAD DE DATOS

## GESTIÓN DE CATEGÓRICAS

In [ ]:
def estadisticos_cont(df_cat):
    #Calculamos describe
    estadisticos = df_cat.describe().T
    return(estadisticos)

estadisticos_cont(cat)

                      count unique                      top  freq
origen                 5316      4  Landing Page Submission  3403
fuente                 5316      6                   Google  2046
no_enviar_email        5316      2                       No  4825
no_llamar              5316      2                       No  5314
ult_actividad          5316      8             Email Opened  2011
ambito                 5316     13                   Select  1350
ocupacion              5316      4               Unemployed  4723
conociste_google       5316      2                       No  5307
conociste_periodico    5316      2                       No  5315
conociste_facebook     5316      2                       No  5313
conociste_referencias  5316      2                       No  5312
descarga_lm            5316      2                       No  3310

In [ ]:
def graficos_eda_categoricos(df_cat):
    
    #Calculamos el número de filas que necesitamos
    from math import ceil
    filas = ceil(df_cat.shape[1] / 2)

    #Definimos el gráfico
    f, ax = plt.subplots(nrows = filas, ncols = 2, figsize = (16, filas * 6))

    #Aplanamos para iterar por el gráfico como si fuera de 1 dimensión en lugar de 2
    ax = ax.flat 

    #Creamos el bucle que va añadiendo gráficos
    for cada, variable in enumerate(df_cat):
        df_cat[variable].value_counts(ascending = True).plot.barh(ax = ax[cada])
        ax[cada].set_title(variable, fontsize = 8, fontweight = "bold")
        ax[cada].tick_params(labelsize = 8)
                
graficos_eda_categoricos(cat)

- **Conclusión:** No se aprecian valores únicos.